// Generated by Wrangler on Sat May 25 2024 19:48:48 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_SIGN_IN_URL: string;
	CLERK_SIGN_UP_URL: string;
	CLERK_SIGN_IN_FALLBACK_URL: string;
	CLERK_SIGN_UP_FALLBACK_URL: string;
	DB: D1Database;
}
