// Generated by Wrangler on Mon May 27 2024 12:04:32 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	CLERK_SIGN_IN_URL: "/logg-inn";
	CLERK_SIGN_UP_URL: "/registrer";
	CLERK_SIGN_IN_FALLBACK_URL: "/";
	CLERK_SIGN_UP_FALLBACK_URL: "/";
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	OPENAI_API_KEY: string;
	DB: D1Database;
}
